name: .NET 8.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Launcher.csproj

    - name: Publish
      run: dotnet publish Launcher.csproj

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Launcher
        path: Launcher.exe
